// prisma.config.ts
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// prisma.config.ts
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
        // ADD "tsx" BEFORE THE PATH
        seed: "tsx prisma/seed.ts",
    },
    datasource: {
        url: env("DATABASE_URL"),
    },
});

// import "dotenv/config";
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//     schema: "prisma/schema.prisma",
//     migrations: {
//         path: "prisma/migrations",
//         seed: "tsx prisma/seed.ts",
//     },
//     datasource: {
//         url: env("DATABASE_URL"),
//         shadowDatabaseUrl: env("DIRECT_URL"),
//     },
// });
