name: Remote Deploy to AWS EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Executing remote ssh commands using ssh-key
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: admin
                  key: ${{ secrets.EC2_SSH_KEY }}
                  port: 22
                  script: |
                      cd /home/admin/Eventify-ABCD

                      # 1. Pull the absolute fresh code
                      git fetch --all
                      git reset --hard origin/main

                      # 2. Install dependencies & wipe old permission-locked folders
                      npm install
                      sudo rm -rf .next

                      # 3. Build the new code fresh
                      npm run build

                      # 4. Reload PM2 safely using the direct binary route
                      pm2 delete eventify || true
                      sudo fuser -k 3000/tcp || true
                      pm2 start node_modules/next/dist/bin/next --name "eventify" -- start -- -p 3000 -H 0.0.0.0
                      pm2 save
